[package]
name = "tamago"
version = "0.1.0"
authors = ["Ziyan Wang <zywong159@gmail.com>"]

[lib] 
crate-type = ["staticlib"]

[dependencies]
spin = "0.4.8" 
volatile = "0.2.4"
multiboot2 = "0.1.0" 

[profile.release]
panic = "abort" 
